spring:
  application:
    name: demoConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config


server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
